# Generated by Django 4.1.7 on 2023-06-27 07:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
